### ISSUE TITLE
what is version for Lr-LiVAE??

### ISSUE THREAD

**Issue by Johnson-yue** [johnnyasd12/LrLiVAE#1]
Hi,  I see you create a empty for this paper, and official implement have release a tf version.
So, what is version in this repo ???

**Comment by johnnyasd12** [comment]
Hi, I was going to implement Lr-LiVAE with PyTorch because the official repository had not uploaded the code when I create this repository, but then they did. Therefore, I don't think I would update this repository and may delete this repo afterward. 
Thank you.

**Comment by Johnson-yue** [comment]
ok, but upload is tensorflow version ..thank you for reply, I want to implement it with pytorch
